version: '3.8'

services:
  frigate-alerter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frigate-alerter
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json:ro
    ports:
      - "${SERVER_PORT:-5555}:${SERVER_PORT:-5555}"
    environment:
      - FRIGATE_SERVER=${FRIGATE_SERVER:-192.168.200.1}
      - FRIGATE_PORT=${FRIGATE_PORT:-5000}
      - MQTT_SERVER=${MQTT_SERVER:-tcp://192.168.200.1:1883}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - TIME_ZONE=${TIME_ZONE:-Asia/Kolkata}
      - SERVER_PORT=${SERVER_PORT:-5555}
    networks:
      - frigate-network

networks:
  frigate-network:
    driver: bridge
